"""Helpers for previewing a single PsyNet page in debug mode."""

from __future__ import annotations

import json
import os
import shutil
import subprocess
import tempfile
from contextlib import contextmanager
from pathlib import Path
from textwrap import dedent
from typing import Iterator, Optional

MIRRORED_PREVIEW_PATHS = (
    "assets",
    ".gitignore",
    "config.txt",
    "constraints.txt",
    "requirements.txt",
    "static",
    "templates",
)


def parse_page_target(target: str) -> tuple[str, str]:
    """Parse a page factory target.

    Parameters
    ----------
    target
        Target in ``module:attribute`` form. The module part can be an import
        name or a Python file path relative to the experiment directory.

    Returns
    -------
    tuple
        The module target and dotted attribute path.
    """
    module_name, separator, attribute_path = target.partition(":")
    if not separator or not module_name or not attribute_path:
        raise ValueError(
            "Page factory must use MODULE:ATTRIBUTE syntax, for example "
            "`experiment.py:preview_page`."
        )
    return module_name, attribute_path


def build_preview_experiment_source(target: str, experiment_root: Path) -> str:
    """Build the source code for a one-page preview experiment."""
    parse_page_target(target)
    return dedent(
        f"""
        # Auto-generated by `psynet dev preview-page`.
        import importlib
        import importlib.util
        import pathlib
        import sys

        import psynet.experiment
        from psynet.timeline import PageMaker, Timeline
        from psynet.utils import call_function_with_context


        _ORIGINAL_ROOT = pathlib.Path({json.dumps(str(experiment_root.resolve()))})
        _PAGE_TARGET = {json.dumps(target)}


        def _load_module_from_path(path):
            path = pathlib.Path(path)
            if not path.is_absolute():
                path = _ORIGINAL_ROOT / path
            path = path.resolve()
            module_name = "_psynet_page_preview_" + path.stem
            spec = importlib.util.spec_from_file_location(module_name, path)
            if spec is None or spec.loader is None:
                raise ImportError(f"Could not import page preview module from {{path}}.")
            module = importlib.util.module_from_spec(spec)
            spec.loader.exec_module(module)
            return module


        def _load_module(module_name):
            if str(_ORIGINAL_ROOT) not in sys.path:
                sys.path.insert(0, str(_ORIGINAL_ROOT))
            if module_name == "experiment":
                return _load_module_from_path(_ORIGINAL_ROOT / "experiment.py")
            if module_name.endswith(".py") or "/" in module_name or "\\\\" in module_name:
                return _load_module_from_path(module_name)
            return importlib.import_module(module_name)


        def _resolve_target():
            module_name, attribute_path = _PAGE_TARGET.split(":", 1)
            value = _load_module(module_name)
            for part in attribute_path.split("."):
                value = getattr(value, part)
            return value


        def _preview_page(experiment, participant):
            return call_function_with_context(
                _resolve_target(),
                experiment=experiment,
                participant=participant,
            )


        class Exp(psynet.experiment.Experiment):
            timeline = Timeline(
                PageMaker(
                    _preview_page,
                    time_estimate=1.0,
                    label="page_preview",
                )
            )
        """
    ).lstrip()


def create_preview_experiment(
    target: str,
    *,
    experiment_root: Path,
    preview_root: Path,
) -> Path:
    """Create a one-page preview experiment directory."""
    experiment_root = experiment_root.resolve()
    preview_root.mkdir(parents=True, exist_ok=True)
    _write_preview_experiment(target, experiment_root, preview_root)
    _mirror_preview_paths(experiment_root, preview_root)
    _write_default_preview_files(preview_root)
    _initialize_preview_git_repository(preview_root)
    return preview_root


@contextmanager
def preview_experiment_directory(
    target: str, experiment_root: Optional[Path] = None
) -> Iterator[Path]:
    """Create a temporary preview experiment directory."""
    experiment_root = Path.cwd() if experiment_root is None else experiment_root
    with tempfile.TemporaryDirectory(prefix="psynet-page-preview-") as tempdir:
        yield create_preview_experiment(
            target,
            experiment_root=experiment_root,
            preview_root=Path(tempdir),
        )


def _write_preview_experiment(
    target: str, experiment_root: Path, preview_root: Path
) -> None:
    """Write the generated ``experiment.py`` file."""
    source = build_preview_experiment_source(target, experiment_root)
    (preview_root / "experiment.py").write_text(source, encoding="utf-8")


def _mirror_preview_paths(experiment_root: Path, preview_root: Path) -> None:
    """Mirror common experiment paths into the preview directory."""
    for name in MIRRORED_PREVIEW_PATHS:
        source = experiment_root / name
        if source.exists():
            _mirror_path(source, preview_root / name)


def _mirror_path(source: Path, destination: Path) -> None:
    """Mirror a file or directory by symlink, falling back to copying."""
    if destination.exists() or destination.is_symlink():
        return

    try:
        os.symlink(source, destination, target_is_directory=source.is_dir())
        return
    except OSError:
        pass

    if source.is_dir():
        shutil.copytree(source, destination, symlinks=True)
    else:
        shutil.copy2(source, destination)


def _write_default_preview_files(preview_root: Path) -> None:
    """Write minimal experiment files required by ``psynet debug local``."""
    defaults = {
        ".gitignore": "source_code.zip\nserver.log\nlogs.jsonl\n.deploy/\n",
        "config.txt": (
            "[Config]\n"
            "title = PsyNet page preview\n"
            "description = Preview a single PsyNet page.\n"
            "contact_email_on_error = preview@example.com\n"
            "organization_name = PsyNet\n"
            "recruiter = generic\n"
            "currency = $\n"
            "wage_per_hour = 12.0\n"
        ),
        "constraints.txt": "",
        "requirements.txt": "",
    }

    for filename, contents in defaults.items():
        path = preview_root / filename
        if not path.exists() and not path.is_symlink():
            path.write_text(contents, encoding="utf-8")


def _initialize_preview_git_repository(preview_root: Path) -> None:
    """Make the temporary preview directory pass local debug git checks."""
    if (preview_root / ".git").exists():
        return
    subprocess.run(
        ["git", "init", "--quiet"],
        cwd=preview_root,
        check=True,
    )
