image: docker:26.1.1

services:
  - docker:26.1.1-dind
  - postgres:16-bookworm
  - redis:latest

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  POSTGRES_DB: dallinger
  POSTGRES_USER: dallinger
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://dallinger@postgres:5432/dallinger
  REDIS_URL: redis://redis:6379
  HEADLESS: "TRUE"
  DOCKER_LOCAL_TAG: psynet-build
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - export POSTGRES_IP=$(getent ahostsv4 postgres | awk '{ print $1 }' | tail -n 1)
  - export REDIS_IP=$(getent ahostsv4 redis | awk '{ print $1 }' | tail -n 1)
  - echo $POSTGRES_IP
  - echo $REDIS_IP
  - docker build --tag $DOCKER_LOCAL_TAG .

.default_rules: &default_rules
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - if: $CI_COMMIT_BRANCH
      when: always
    - if: $CI_COMMIT_TAG
      when: always

pre_commit:
  image: python:3.13
  <<: *default_rules
  before_script:
    - pip install pre-commit
  script:
    - pre-commit run --all-files

changelog_check:
  image:
    name: alpine/git
    entrypoint: ["/bin/sh", "-c"]
  stage: test
  before_script: []
  script:
    - |
      git fetch --quiet origin $CI_MERGE_REQUEST_TARGET_BRANCH_NAME
      CHANGED_FILES=$(git diff --name-only origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME...$CI_COMMIT_SHA)
      if ! echo "$CHANGED_FILES" | grep -q 'CHANGELOG.md'; then
        echo "ERROR: Merge requests must include a corresponding entry in CHANGELOG.md."
        exit 1
      fi
  rules:
    - if: $CI_MERGE_REQUEST_ID
      when: always
    - when: never

tests:
  parallel: 10
  stage: test
  <<: *default_rules
  script:
    - export PSYNET_WORKSPACE=/root/workspaces/PsyNet
    - docker run
      --add-host=postgres:$POSTGRES_IP
      --add-host=redis:$REDIS_IP
      -e HEADLESS=TRUE -e REDIS_URL -e DATABASE_URL -e POSTGRES_DB -e POSTGRES_USER -e POSTGRES_PASSWORD
      -e AWS_ACCESS_KEY_ID -e AWS_DEFAULT_REGION -e AWS_SECRET_ACCESS_KEY
      -e CI_NODE_TOTAL -e CI_NODE_INDEX
      -e CI_COMMIT_REF_NAME
      -e PSYNET_WORKSPACE
      -v "$PWD:$PSYNET_WORKSPACE"
      -v "$PWD/public:/public"
      -w $PSYNET_WORKSPACE
      $DOCKER_LOCAL_TAG bash -c "bash run-ci-tests.sh"
  artifacts:
    paths:
      - public/

merge_test_results:
  image: python:3.13-alpine
  stage: test
  <<: *default_rules
  needs: ["tests"]
  dependencies: ["tests"]
  when: always
  before_script:
    - pip install -q junitparser
  script:
    - ls -la public
    - junitparser merge public/*junit.xml junit.xml || echo "<testsuite></testsuite>" > junit.xml
  artifacts:
    reports:
      junit: junit.xml

# To do:
# - Skip tests if the changes are only in the docs directory
pages:
  image: python:3.13
  stage: deploy
  before_script: []
  script:
    - pip install -e '.[dev]'
    - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v[0-9]+\.[0-9]+\.[0-9]+$/
      when: always
    - when: never

