image: python:3.7.0

pages:
  stage: deploy
  script:
  - pip install psycopg2-binary
  - pip install .
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinx-autodoc-typehints
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - dev
  - refactor
