image: python:3.7.0

before_script:
  - pip install -e .[test]

tests:
  stage: test
  script:
  - python setup.py test

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinx-autodoc-typehints
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - dev
  - refactor
