image: python:3.7.0

before_script:
  - uname -a
  - sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt $(lsb_release -cs)-pgdg main" > /etc/apt/sources.list.d/pgdg.list'
  - wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
  - apt-get update
  - apt-get install postgresql
  - createuser dallinger --createdb
  - createdb -O dallinger dallinger
  - createdb -O dallinger dallinger-import-bartlett-test
  - pip install dallinger[dev]
  - pip install -e .[dev]

tests:
  stage: test
  script:
  - pytest tests/

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinx-autodoc-typehints
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - dev
  - refactor
