image: python:3.7

services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: dallinger
  POSTGRES_USER: dallinger
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://dallinger@postgres:5432/dallinger

before_script:
  - apt-get update
  - apt-get -f -y install python-enchant
  - git clone https://github.com/Dallinger/Dallinger.git /tmp/dallinger
  - WD=`pwd`
  - cd /tmp/dallinger
  - git checkout v7.0.0
  - cd $WD
  - pip install -r /tmp/dallinger/dev-requirements.txt
  - pip install -e /tmp/dallinger[data]
  - pip install -e .[dev]

tests:
  stage: test
  script:
  - apt-get update
  - curl https://cli-assets.heroku.com/install.sh | sh
  - apt-get -f -y install curl redis-server
  - service redis-server start
  - wget -O chrome.deb https://dl.google.com/linux/chrome/deb/pool/main/g/google-chrome-stable/google-chrome-stable_88.0.4324.150-1_amd64.deb
  - wget -O chrome-driver.zip https://chromedriver.storage.googleapis.com/88.0.4324.96/chromedriver_linux64.zip
  - apt-get -f -y install ./chrome.deb
  - apt-get -f -y install -yqq unzip
  - unzip chrome-driver.zip chromedriver -d /usr/local/bin/
  - export HEADLESS=TRUE
  - pytest --chrome tests/

pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinx-autodoc-typehints
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
