image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - postgres:12.2-alpine
  - redis:latest

variables:
  AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
  AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
  AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
  POSTGRES_DB: dallinger
  POSTGRES_USER: dallinger
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://dallinger@postgres:5432/dallinger
  REDIS_URL: redis://redis:6379
  HEADLESS: "TRUE"
  DOCKER_REGISTRY_BASE: registry.gitlab.com/psynetdev/psynet
  DOCKER_IMAGE_CACHE_FROM: "$DOCKER_REGISTRY_BASE:master"
  DOCKER_LOCAL_TAG: psynet-build
  DOCKER_REMOTE_TAG: "$DOCKER_REGISTRY_BASE:$CI_COMMIT_REF_NAME"
  DOCKER_HOST: tcp://docker:2375
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""

before_script:
  - export POSTGRES_IP=$(getent hosts postgres  | awk '{ print $1 }')
  - export REDIS_IP=$(getent hosts redis  | awk '{ print $1 }')
  - echo $POSTGRES_IP
  - echo $REDIS_IP
  - docker image prune --all --force
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $DOCKER_IMAGE_CACHE_FROM || true
  - docker build --cache-from $DOCKER_IMAGE_CACHE_FROM --tag $DOCKER_LOCAL_TAG .


pg_badger:
  image: python:3.11.6-alpine
  services: []
  cache:
      key: "$CI_BUILD_REF_NAME"
      paths:
      - venv/
  before_script:
    # - echo Install Heroku CLI and docker
    # - curl https://cli-assets.heroku.com/install.sh | sh
    # - curl https://get.docker.com/builds/Linux/x86_64/docker-latest.tgz | tar xzf - -C /usr/local
    # - ln -s /usr/local/docker/docker /usr/local/bin/
    # - echo "Starting postgresql server with aggressive logging enabled (via docker)"
    # - docker run --rm -d --name dallinger_postgres -p 5432:5432 -e POSTGRES_USER=dallinger -e POSTGRES_PASSWORD=dallinger -e POSTGRES_DB=dallinger -v dallinger_postgres:/var/lib/postgresql/data postgres:12 postgres -c log_statement=all -c log_min_messages=DEBUG1 -c log_duration=on
    - echo Create a virtualenv and install psynet there
    - pip install --upgrade pip virtualenv
    - virtualenv venv -ppython3
    - . venv/bin/activate
    - which pip
    - which python
    # - pip install -e .[dev] pytest
    # - |
    #   until docker exec -i dallinger_postgres pg_isready; do
    #     echo "Waiting for PostgreSQL to become ready..."
    #     sleep 1
    #   done
    - echo foo
  script:
    - pwd
    - cd "demos/$TEST_NAME"
    - pwd
    # - DATABASE_URL="postgresql://dallinger:dallinger@docker:5432/dallinger" psynet test local > /dev/null
  after_script:
    - cat junit_tmp.xml > junit.xml
    - pwd
    # - docker logs dallinger_postgres 2> postgresql.log > /dev/null
    # - curl -L https://github.com/darold/pgbadger/archive/refs/tags/v12.4.tar.gz | tar xzf - -C /usr/local
    # - (cd /usr/local/pgbadger-*; perl Makefile.PL; make; make install)
    # - pgbadger postgresql.log -o /tmp/pgbadger.html
    # - mkdir public
    # - cp /tmp/pgbadger.html "public/${TEST_NAME//\//_}.html"
    # - pgbadger postgresql.log -o /tmp/pgbadger.txt
    # - echo "Check the full pgbadger analysis at the following URL:" >> /tmp/pgbadger.txt
    # - echo "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/${TEST_NAME//\//_}.html" >> /tmp/pgbadger.txt
    # - venv/bin/python ci/generate_junit_xml.py --classname "$TEST_NAME" --testname="pgbadger" < /tmp/pgbadger.txt > junit.xml
  artifacts:
    paths:
      - public
    expire_in: 1 week
    reports:
      junit: junit.xml
  environment:
      name: PgBadger-$CI_COMMIT_BRANCH-$TEST_NAME
      url: "https://$CI_PROJECT_NAMESPACE.gitlab.io/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public/$TEST_NAME.html"
  variables:
      PUBLIC_URL: "/-/$CI_PROJECT_NAME/-/jobs/$CI_JOB_ID/artifacts/public"
      TEST_NAME: rock_paper_scissors
  parallel:
    matrix:
      - TEST_NAME: ["rock_paper_scissors", "slider"]
