# The following workflow runs:
# - Branch pipelines when a merge request is not open for the branch.
# - Merge request pipelines when a merge request is open for the branch.
# See https://docs.gitlab.com/ee/ci/yaml/workflow.html for more details.
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
#    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
#      when: never
#    - if: $CI_COMMIT_BRANCH

image: docker:20.10.16

services:
  - docker:20.10.16-dind
  - postgres:12.2-alpine
  - redis:latest

# TODO - build on tags

variables:
  POSTGRES_DB: dallinger
  POSTGRES_USER: dallinger
  POSTGRES_PASSWORD: ""
  POSTGRES_HOST_AUTH_METHOD: trust
  DATABASE_URL: postgresql://dallinger@postgres:5432/dallinger
  REDIS_URL: redis://redis:6379
  HEADLESS: "TRUE"
  DOCKER_IMAGE: $CI_REGISTRY_IMAGE:$CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker pull $DOCKER_IMAGE || true
  - docker build --cache-from $DOCKER_IMAGE --tag $DOCKER_IMAGE .

tests:
  parallel: 5
  stage: test
  script:
    - docker run -p 5432:5432 -p 6379:6379 $DOCKER_IMAGE bash -c "pytest --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX --test-group-random-seed=12345 --ignore=tests/local_only tests --chrome tests"

tests_isolated:
  stage: test
  script:
    - docker run -p 5432:5432 -p 6379:6379 $DOCKER_IMAGE bash -c "pytest --chrome tests/isolated/test_demo_gibbs.py"

deploy_docker:
  stage: deploy
  script:
    - docker push $DOCKER_IMAGE

pages:
  image: $DOCKER_IMAGE
  stage: deploy
  script:
    - TODO
    - pip install -U sphinx
    - pip install sphinx_rtd_theme
    - pip install sphinx-autodoc-typehints
    - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - master
