# Comment this out if you decide to use local postgres instead
services:
  - postgres:12.2-alpine

variables:
  POSTGRES_DB: dallinger
  POSTGRES_USER: dallinger
  POSTGRES_PASSWORD: "dallinger"
  DATABASE_URL: postgresql://dallinger:dallinger@localhost:5432/dallinger

build:
  image: docker:20.10.16
  stage: build
  services:
    - docker:20.10.16-dind
  variables:
    # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
    DOCKER_HOST: tcp://docker:2376
    DOCKER_TLS_CERTDIR: "/certs"
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker pull $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:CI_COMMIT_BRANCH --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:CI_COMMIT_BRANCH .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_BRANCH

tests:
  image: $CI_REGISTRY_IMAGE:CI_COMMIT_BRANCH
  parallel: 5
  stage: test
  script:
    - pytest --test-group-count $CI_NODE_TOTAL --test-group=$CI_NODE_INDEX --test-group-random-seed=12345 --ignore=tests/local_only tests --chrome tests

tests_isolated:
  image: $CI_REGISTRY_IMAGE:CI_COMMIT_BRANCH
  stage: test
  script:
    - pytest --chrome tests/isolated/test_demo_gibbs.py

pages:
  image: $CI_REGISTRY_IMAGE:CI_COMMIT_BRANCH
  stage: deploy
  script:
    - pip install -U sphinx
    - pip install sphinx_rtd_theme
    - pip install sphinx-autodoc-typehints
    - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - master
