image: nickgryg/alpine-pandas

before_script:
  - apk add gcc gfortran musl-dev # Needed for numpy

pages:
  stage: deploy
  script:
  - pip install .
  - pip install -U sphinx
  - pip install sphinx_rtd_theme
  - pip install sphinx-autodoc-typehints
  - sphinx-build -b html docs public
  artifacts:
    paths:
    - public
    - public/low_level
  only:
  - dev
