repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.15.6
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        types: [python]
        files: ^(tests|psynet|demos|docs)/
      - id: ruff-format
        types: [python]
        files: ^(tests|psynet|demos|docs)/
