[pytest]
norecursedirs = [tests/isolated, tests/template_experiment_tests]

; Filter out the fork deprecation warning; apparently this is not something
; we need to worry about (see https://github.com/gevent/gevent/issues/2052).
filterwarnings = ignore:This process.*is multi-threaded, use of fork.*may lead to deadlocks in the child:DeprecationWarning
