#!/usr/bin/env python
"""
A python script that takes a text file generated by pgbadger and
outputs a junit XML file containing that file as summary.
--classname and --testname are optional arguments that can be passed.
It uses `click` to get user arguments.
"""
import re

import click

JUNIT_TEMPLATE = """
<?xml version="1.0" encoding="UTF-8"?>
<testsuites time="{totaltime}">
    <testsuite name="{suitename}" tests="{totaltests}" errors="0" failures="0" skip="0" time="{totaltime}">
        <system-out>
            <![CDATA[
                {text}
            ]]>
        </system-out>
        <testcase classname="{classname}" name="{testname}" time="{totaltime}" />
    </testsuite>
</testsuites>
"""


def extract_summary(text):
    """
    Extracts the summary from the pgbadger text file
    """
    cutoff = "Hourly statistics"
    lines = text.split('\n')
    for i, line in enumerate(lines):
        if cutoff in line:
            result = '\n'.join(lines[:i + 1])
            break
    return result


def get_num_queries(text):
    num_queries = re.search(r'Number of queries: ([\d,]+)', text)
    return int(num_queries.group(1).replace(',', '')) if num_queries else None


def get_duration(text):
    query_duration = re.search(r'Total query duration: (\d+)s(\d+)ms', text)
    if query_duration:
        seconds = int(query_duration.group(1))
        milliseconds = int(query_duration.group(2))
        return seconds + milliseconds / 1000
    else:
        return None


@click.command()
@click.option('--classname', default='', help='The classname of the test')
@click.option('--testname', default='', help='The name of the test')
@click.argument('pgbadger_file', type=click.File('r'))
def main(classname, testname, pgbadger_file):
    text = pgbadger_file.read()
    num_queries = get_num_queries(text)
    duration = get_duration(text)
    junit_xml = JUNIT_TEMPLATE.format(
        suitename='pgbadger',
        classname=classname,
        testname=testname,
        totaltests=num_queries,
        totaltime=duration,
        text=extract_summary(text)
    )
    click.get_text_stream('stdout').write(junit_xml)


if __name__ == '__main__':
    main()
