#!/usr/bin/env python3

# Run me as follows: python3 demos/update_gitignore.py

import os
import pathlib


def find_demo_dirs():
    """
    Returns
    -------

    A list of directory paths for each of the PsyNet demos.
    These are found by recursively searching in the demos directory
    for all directories containing an experiment.py file.
    """

    root_dir = pathlib.Path(__file__).parent.resolve()
    return sorted(
        [dir for dir, sub_dirs, files in os.walk(root_dir) if "experiment.py" in files]
    )


for dir in find_demo_dirs():
    path = os.path.join(dir, ".gitignore")
    with open(path, "w") as f:
        lines = [
            "# This file is autogenerated, please update it by editing demos/update_gitignore.py.",
            "",
            "# Standard place to put a virtual environment",
            "env/",
            "",
            "# Automatically generated deployment resources, e.g. database templates",
            "deploy/",
            "",
            "# Automatically generated resources for hot-fresh debugger",
            "/develop",
            "",
            "# Automatically generated server log file",
            "server.log",
            "",
            "# Automatically generated resources for debugging experiments with debug storage",
            "static/debug_storage",
        ]
        f.write("\n".join(lines))
