# Run me as follows: python3 demos/update_demos.py
#
# Warning: the chosen constraints will depend on the version of Dallinger that you currently have installed.
# In general, you want to make sure you have installed the version of Dallinger stated in PsyNet's setup.py.
#
# Warning: this command currently takes several minutes to complete because generating constraints.txt files is slow.
# We plan to remove these constraints.txt files in due course from PsyNet, but currently they are required for
# Dallinger back-compatibility.
# In the meantime, if you want to skip generating constraints and only update other demo files,
# set skip_contraints = False before running the script.

import os
import pathlib
import subprocess

from joblib import Parallel, delayed

import psynet.command_line
from psynet.utils import working_directory

skip_constraints = False


def find_demo_dirs():
    """
    Returns
    -------

    A list of directory paths for each of the PsyNet demos.
    These are found by recursively searching in the demos directory
    for all directories containing an experiment.py file.
    """

    root_dir = pathlib.Path(__file__).parent.resolve()
    return sorted(
        [
            dir
            for dir, sub_dirs, files in os.walk(root_dir)
            if "experiment.py" in files and not dir.endswith("/develop")
        ]
    )


def update_demo(dir):
    update_scripts(dir)
    update_gitignore(dir)
    if not skip_constraints:
        generate_constraints(dir)


def generate_constraints(dir):
    subprocess.run(
        "dallinger generate-constraints",
        shell=True,
        cwd=dir,
        capture_output=True,
    )


def update_scripts(dir):
    with working_directory(dir):
        psynet.command_line.update_scripts_()


def update_gitignore(dir):
    path = os.path.join(dir, ".gitignore")
    with open(path, "w") as f:
        lines = [
            "# This file is autogenerated, please update it by editing demos/update_gitignore.py.",
            "",
            "# Standard place to put a virtual environment",
            "env/",
            "",
            "# Automatically generated deployment resources, e.g. database templates",
            ".deploy/",
            "",
            "# Deployment logs",
            "deploy_logs/",
            "",
            "# Automatically generated resources for hot-fresh debugger",
            "/develop",
            "",
            "# Automatically generated server log file",
            "server.log",
            "",
            "# Automatically generated resources for running experiments with assets",
            "static/assets",
            "",
            "# PyCharm configuration file",
            ".idea",
            "",
            "# Python cache files",
            "__pycache__",
            "",
            "# MacOS Finder config files",
            "*.DS_Store",
            "",
        ]
        f.write("\n".join(lines))


if skip_constraints:
    n_jobs = 1
else:
    n_jobs = 16

Parallel(verbose=10, n_jobs=n_jobs)(
    delayed(update_demo)(_dir) for _dir in find_demo_dirs()
)
